version: "3.8"

networks:
  default:
    external:
      name: describo-local_default

volumes:
    database_volume:
        driver: local

services:
    db:
        image: postgres:13-alpine
        hostname: db
        tty: true
        environment:
            TERM: "xterm-256color"
            POSTGRES_DB: "describo"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
            PGDATA: /postgresql/data
        volumes:
            - database_volume:/postgresql
    
    reva:
        image: arkisto/describo-reva
        hostname: reva-gateway
        tty: true
        working_dir: "/srv/reva"
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
        volumes:
            - ./reva-configuration:/etc/revad
            - ${DATA}:/var/tmp/reva
        command: bash -c "./revad --dev-dir /etc/revad"

    api:
        image: arkisto/describo-online-api:latest
        hostname: api
        tty: true
        environment:
            TERM: "xterm-256color"
            DB_HOST: "db"
            DB_PORT: "5432"
            DB_USER: "admin"
            DB_PASSWORD: "admin"
            DB_DATABASE: "describo"
        volumes:
            - ./describo-configuration.json:/srv/configuration.json
            - ./profiles:/srv/profiles

    ui:
        image: arkisto/describo-online-ui:latest
        hostname: ui
        tty: true
        environment:
            TERM: "xterm-256color"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80